-- Annales 1 Bac : examens régionaux Français + Histoire-Géo 2022 et 2023 (PDF officiels).
SET SESSION sql_mode = CONCAT(@@sql_mode, ',NO_BACKSLASH_ESCAPES');
SET @fr := (SELECT id FROM matiere WHERE slug = 'francais-1bac');
SET @hg := (SELECT id FROM matiere WHERE slug = 'histoire-geo-1bac');
INSERT INTO annale (id, matiere_id, titre, annee, session, sujet_url, corrige_url) VALUES
 (450, @fr, 'Examen régional Français — Béni Mellal-Khénifra (2022)', 2022, 'NORMALE', '/annales/francais-1bac-2022-beni-mellal-khenifra-sujet.pdf', '/annales/francais-1bac-2022-beni-mellal-khenifra-corrige.pdf'),
 (451, @fr, 'Examen régional Français — Casablanca-Settat (2022)', 2022, 'NORMALE', '/annales/francais-1bac-2022-casablanca-settat-sujet.pdf', '/annales/francais-1bac-2022-casablanca-settat-corrige.pdf'),
 (452, @fr, 'Examen régional Français — Dakhla-Oued Ed-Dahab (2022)', 2022, 'NORMALE', '/annales/francais-1bac-2022-dakhla-oued-ed-dahab-sujet.pdf', NULL),
 (453, @fr, 'Examen régional Français — Drâa-Tafilalet (2022)', 2022, 'NORMALE', '/annales/francais-1bac-2022-draa-tafilalet-sujet.pdf', '/annales/francais-1bac-2022-draa-tafilalet-corrige.pdf'),
 (454, @fr, 'Examen régional Français — Fès-Meknès (2022)', 2022, 'NORMALE', '/annales/francais-1bac-2022-fes-meknes-sujet.pdf', '/annales/francais-1bac-2022-fes-meknes-corrige.pdf'),
 (455, @fr, 'Examen régional Français — Guelmim-Oued Noun (2022)', 2022, 'NORMALE', '/annales/francais-1bac-2022-guelmim-oued-noun-sujet.pdf', '/annales/francais-1bac-2022-guelmim-oued-noun-corrige.pdf'),
 (456, @fr, 'Examen régional Français — Laâyoune-Sakia El Hamra (2022)', 2022, 'NORMALE', '/annales/francais-1bac-2022-laayoune-sakia-el-hamra-sujet.pdf', '/annales/francais-1bac-2022-laayoune-sakia-el-hamra-corrige.pdf'),
 (457, @fr, 'Examen régional Français — Marrakech-Safi (2022)', 2022, 'NORMALE', '/annales/francais-1bac-2022-marrakech-safi-sujet.pdf', '/annales/francais-1bac-2022-marrakech-safi-corrige.pdf'),
 (458, @fr, 'Examen régional Français — Rabat-Salé-Kénitra (2022)', 2022, 'NORMALE', '/annales/francais-1bac-2022-rabat-sale-kenitra-sujet.pdf', NULL),
 (459, @fr, 'Examen régional Français — Tanger-Tétouan-Al Hoceïma (2022)', 2022, 'NORMALE', '/annales/francais-1bac-2022-tanger-tetouan-al-hoceima-sujet.pdf', '/annales/francais-1bac-2022-tanger-tetouan-al-hoceima-corrige.pdf'),
 (430, @fr, 'Examen régional Français — Béni Mellal-Khénifra (2023)', 2023, 'NORMALE', '/annales/francais-1bac-2023-beni-mellal-khenifra-sujet.pdf', '/annales/francais-1bac-2023-beni-mellal-khenifra-corrige.pdf'),
 (431, @fr, 'Examen régional Français — Casablanca-Settat (2023)', 2023, 'NORMALE', '/annales/francais-1bac-2023-casablanca-settat-sujet.pdf', '/annales/francais-1bac-2023-casablanca-settat-corrige.pdf'),
 (432, @fr, 'Examen régional Français — Dakhla-Oued Ed-Dahab (2023)', 2023, 'NORMALE', '/annales/francais-1bac-2023-dakhla-oued-ed-dahab-sujet.pdf', NULL),
 (433, @fr, 'Examen régional Français — Drâa-Tafilalet (2023)', 2023, 'NORMALE', '/annales/francais-1bac-2023-draa-tafilalet-sujet.pdf', '/annales/francais-1bac-2023-draa-tafilalet-corrige.pdf'),
 (434, @fr, 'Examen régional Français — Fès-Meknès (2023)', 2023, 'NORMALE', '/annales/francais-1bac-2023-fes-meknes-sujet.pdf', '/annales/francais-1bac-2023-fes-meknes-corrige.pdf'),
 (435, @fr, 'Examen régional Français — Guelmim-Oued Noun (2023)', 2023, 'NORMALE', '/annales/francais-1bac-2023-guelmim-oued-noun-sujet.pdf', '/annales/francais-1bac-2023-guelmim-oued-noun-corrige.pdf'),
 (436, @fr, 'Examen régional Français — Laâyoune-Sakia El Hamra (2023)', 2023, 'NORMALE', '/annales/francais-1bac-2023-laayoune-sakia-el-hamra-sujet.pdf', '/annales/francais-1bac-2023-laayoune-sakia-el-hamra-corrige.pdf'),
 (437, @fr, 'Examen régional Français — Souss-Massa (2023)', 2023, 'NORMALE', '/annales/francais-1bac-2023-souss-massa-sujet.pdf', NULL),
 (438, @fr, 'Examen régional Français — Tanger-Tétouan-Al Hoceïma (2023)', 2023, 'NORMALE', '/annales/francais-1bac-2023-tanger-tetouan-al-hoceima-sujet.pdf', '/annales/francais-1bac-2023-tanger-tetouan-al-hoceima-corrige.pdf'),
 (490, @hg, 'Examen régional Histoire-Géo — Béni Mellal-Khénifra (2022)', 2022, 'NORMALE', '/annales/histoire-geo-1bac-2022-beni-mellal-khenifra-sujet.pdf', '/annales/histoire-geo-1bac-2022-beni-mellal-khenifra-corrige.pdf'),
 (491, @hg, 'Examen régional Histoire-Géo — Casablanca-Settat (2022)', 2022, 'NORMALE', '/annales/histoire-geo-1bac-2022-casablanca-settat-sujet.pdf', '/annales/histoire-geo-1bac-2022-casablanca-settat-corrige.pdf'),
 (492, @hg, 'Examen régional Histoire-Géo — Dakhla-Oued Ed-Dahab (2022)', 2022, 'NORMALE', '/annales/histoire-geo-1bac-2022-dakhla-oued-ed-dahab-sujet.pdf', '/annales/histoire-geo-1bac-2022-dakhla-oued-ed-dahab-corrige.pdf'),
 (493, @hg, 'Examen régional Histoire-Géo — Drâa-Tafilalet (2022)', 2022, 'NORMALE', '/annales/histoire-geo-1bac-2022-draa-tafilalet-sujet.pdf', '/annales/histoire-geo-1bac-2022-draa-tafilalet-corrige.pdf'),
 (494, @hg, 'Examen régional Histoire-Géo — Fès-Meknès (2022)', 2022, 'NORMALE', '/annales/histoire-geo-1bac-2022-fes-meknes-sujet.pdf', '/annales/histoire-geo-1bac-2022-fes-meknes-corrige.pdf'),
 (495, @hg, 'Examen régional Histoire-Géo — Guelmim-Oued Noun (2022)', 2022, 'NORMALE', '/annales/histoire-geo-1bac-2022-guelmim-oued-noun-sujet.pdf', '/annales/histoire-geo-1bac-2022-guelmim-oued-noun-corrige.pdf'),
 (496, @hg, 'Examen régional Histoire-Géo — Marrakech-Safi (2022)', 2022, 'NORMALE', '/annales/histoire-geo-1bac-2022-marrakech-safi-sujet.pdf', '/annales/histoire-geo-1bac-2022-marrakech-safi-corrige.pdf'),
 (497, @hg, 'Examen régional Histoire-Géo — Oriental (2022)', 2022, 'NORMALE', '/annales/histoire-geo-1bac-2022-oriental-sujet.pdf', '/annales/histoire-geo-1bac-2022-oriental-corrige.pdf'),
 (498, @hg, 'Examen régional Histoire-Géo — Rabat-Salé-Kénitra (2022)', 2022, 'NORMALE', '/annales/histoire-geo-1bac-2022-rabat-sale-kenitra-sujet.pdf', '/annales/histoire-geo-1bac-2022-rabat-sale-kenitra-corrige.pdf'),
 (499, @hg, 'Examen régional Histoire-Géo — Souss-Massa (2022)', 2022, 'NORMALE', '/annales/histoire-geo-1bac-2022-souss-massa-sujet.pdf', '/annales/histoire-geo-1bac-2022-souss-massa-corrige.pdf'),
 (500, @hg, 'Examen régional Histoire-Géo — Tanger-Tétouan-Al Hoceïma (2022)', 2022, 'NORMALE', '/annales/histoire-geo-1bac-2022-tanger-tetouan-al-hoceima-sujet.pdf', '/annales/histoire-geo-1bac-2022-tanger-tetouan-al-hoceima-corrige.pdf'),
 (470, @hg, 'Examen régional Histoire-Géo — Béni Mellal-Khénifra (2023)', 2023, 'NORMALE', '/annales/histoire-geo-1bac-2023-beni-mellal-khenifra-sujet.pdf', '/annales/histoire-geo-1bac-2023-beni-mellal-khenifra-corrige.pdf'),
 (471, @hg, 'Examen régional Histoire-Géo — Casablanca-Settat (2023)', 2023, 'NORMALE', '/annales/histoire-geo-1bac-2023-casablanca-settat-sujet.pdf', '/annales/histoire-geo-1bac-2023-casablanca-settat-corrige.pdf'),
 (472, @hg, 'Examen régional Histoire-Géo — Dakhla-Oued Ed-Dahab (2023)', 2023, 'NORMALE', '/annales/histoire-geo-1bac-2023-dakhla-oued-ed-dahab-sujet.pdf', NULL),
 (473, @hg, 'Examen régional Histoire-Géo — Drâa-Tafilalet (2023)', 2023, 'NORMALE', '/annales/histoire-geo-1bac-2023-draa-tafilalet-sujet.pdf', '/annales/histoire-geo-1bac-2023-draa-tafilalet-corrige.pdf'),
 (474, @hg, 'Examen régional Histoire-Géo — Fès-Meknès (2023)', 2023, 'NORMALE', '/annales/histoire-geo-1bac-2023-fes-meknes-sujet.pdf', '/annales/histoire-geo-1bac-2023-fes-meknes-corrige.pdf'),
 (475, @hg, 'Examen régional Histoire-Géo — Guelmim-Oued Noun (2023)', 2023, 'NORMALE', '/annales/histoire-geo-1bac-2023-guelmim-oued-noun-sujet.pdf', '/annales/histoire-geo-1bac-2023-guelmim-oued-noun-corrige.pdf'),
 (476, @hg, 'Examen régional Histoire-Géo — Laâyoune-Sakia El Hamra (2023)', 2023, 'NORMALE', '/annales/histoire-geo-1bac-2023-laayoune-sakia-el-hamra-sujet.pdf', '/annales/histoire-geo-1bac-2023-laayoune-sakia-el-hamra-corrige.pdf'),
 (477, @hg, 'Examen régional Histoire-Géo — Oriental (2023)', 2023, 'NORMALE', '/annales/histoire-geo-1bac-2023-oriental-sujet.pdf', '/annales/histoire-geo-1bac-2023-oriental-corrige.pdf'),
 (478, @hg, 'Examen régional Histoire-Géo — Tanger-Tétouan-Al Hoceïma (2023)', 2023, 'NORMALE', '/annales/histoire-geo-1bac-2023-tanger-tetouan-al-hoceima-sujet.pdf', '/annales/histoire-geo-1bac-2023-tanger-tetouan-al-hoceima-corrige.pdf');
